topics:
- name    : keyboard
  topic   : keyboard_teleop/cmd_vel
  timeout : 0.5
  priority: 12
- name    : joy
  topic   : joy_teleop/cmd_vel
  timeout : 0.5
  priority: 10
- name    : follow_lines
  topic   : follow_lines/cmd_vel
  timeout : 0.5
  priority: 6
- name    : uturn
  topic   : uturn/cmd_vel
  timeout : 0.5
  priority: 4
- name    : move_base
  topic   : move_base/cmd_vel
  timeout : 0.5
  priority: 2
- name    : external
  topic   : cmd_vel
  timeout : 0.5
  priority: 1

locks:
- name    : e_stop
  topic   : e_stop
  timeout : 0.0    
  priority: 255
