sudo: required 
dist: trusty 
language: generic 
compiler:
  - gcc
env:
  matrix:
    - USE_DEB=true  ROS_DISTRO="indigo" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu NOT_TEST_BUILD=true
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config  
script: 
  - source .ci_config/travis.sh
